### ISSUE TITLE
Setup alerts on the MPC service

### ISSUE THREAD

**Issue by DavidM-D** [near/mpc-recovery#183]
We need to keep track of
* Whether the nodes are up
* Whether we have an elevated set of errors

Us and SRE need to be alerted if these things change and we need to design a checklist of things to do when something goes wrong.
```[tasklist]
### Tasks
- [x] Set up Prometheus to scrape, collect and monitor metrics
- [x] Set up Alertmanager to dispatch the alerts generated by Prometheus
- [x] Create Grafana board to display the metrics
- [x] Create Alerts
```
