### ISSUE TITLE
Verified communication between front end and signer

### ISSUE THREAD

**Issue by DavidM-D** [near/mpc-recovery#184]
```[tasklist]
### Tasks
- [x] Claiming enpoint and related code
- [x] Client and server (root MPC) signature checks
- [x] DB code for claiming with checks if the ID Token was claimed
- [x] Integration tests
- [x] add_key -> sign change of the API
- [x] Enforce usage of claim_oidc
- [x] new_account FRP issue
- [x] End-to-end testing with new API (including JS)
```
