### ISSUE TITLE
Terraform workflow improvements

### ISSUE THREAD

**Issue by itegulov** [near/mpc-recovery#202]
Having an environment deployed per PR is wasteful as many of them don't need it. Let's figure out a way to do this conditionally; so far I am considering the following options:

1. Wait until the PR author posts a comment, e.g. `terraform deploy`. See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
2. Only do this for PRs that contain `[deploy]` in the title. For example, `feat[deploy]: new ui` will deploy enviornment, while `fix: README` won't
3. Make deploys purely manual. The author will have to go to the Github Action tab, press a button there and enter the PR number.

```[tasklist]
### Tasks
- [ ] Stop running `dev` flow for PRs that don't target `develop` branch
- [ ] Make feature enviornments conditional
- [x] Make workflows wait for lock in case they are being run in parallel
- [ ] Delete feature env workspace after its contents are destroyed
- [ ] (Optional) figure out if it is possible to make `terraform plan` ignore that the currently deployed Docker image is not present on the runner
```
