### ISSUE TITLE
Refactoring, tech debt

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#219]
```[tasklist]
### Tasks
- [x] Refactor Integration Tests, move helpers to a separate entity
- [x] Work on all <30m TODOs
- [ ] https://github.com/near/mpc-recovery/issues/241
- [ ] https://github.com/near/mpc-recovery/issues/218
- [ ] https://github.com/near/mpc-recovery/issues/215
- [ ] https://github.com/near/mpc-recovery/issues/230
- [ ] https://github.com/near/mpc-recovery/issues/231
- [ ] https://github.com/near/mpc-recovery/issues/202
```
