### ISSUE TITLE
🔷 [Epic] Release MPC Recovery with new API

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#242]
```[tasklist]
### Blocking
- [ ] https://github.com/near/mpc-recovery/issues/193
- [ ] https://github.com/near/mpc-recovery/issues/14
- [ ] https://github.com/near/fast-auth-signer/issues/26
```

```[tasklist]
### Nice to have
- [ ] https://github.com/near/mpc-recovery/issues/288
- [ ] https://github.com/near/mpc-recovery/issues/199
- [ ] https://github.com/near/mpc-recovery/issues/246
- [ ] https://github.com/near/mpc-recovery/issues/186
- [ ] https://github.com/near/mpc-recovery/issues/224
- [ ] https://github.com/near/mpc-recovery/issues/235
- [ ] https://github.com/near/mpc-recovery/issues/219
```
