### ISSUE TITLE
🔷 [Epic] FastAuth SDK first release

### ISSUE THREAD

**Issue by DavidM-D** [near/mpc-recovery#248]
This tracks the progress towards the 25th of September release of SDK 1.0 as described in this [document](https://docs.google.com/document/d/1q4eu6ET02aauH8aW4LkGmpY3dW-ir0CQQqv_EqKaFGk/edit).

```[tasklist]
### Tasks
- [ ] https://github.com/near/mpc-recovery/issues/251
- [ ] near/near-discovery#250
- [ ] near/near-discovery#249
- [ ] near/near-discovery#206
- [ ] https://github.com/near/pagoda-relayer-rs-fastauth/issues/20
- [x] Relayers with configurable relayable contracts
- [ ] Open source our version of the relayer
- [ ] https://github.com/near/mpc-recovery/issues/254
- [ ] https://github.com/near/mpc-recovery/issues/253
- [ ] https://github.com/near/mpc-recovery/issues/279
- [ ] https://github.com/near/fast-auth-signer/issues/192
- [ ] https://github.com/near/mpc-recovery/issues/291
- [ ] https://github.com/near/mpc-recovery/issues/203
```
