### ISSUE TITLE
🔷 [Epic] MPC Perfomance and Stability

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#296]
### Description

We should make sure that we are ready to onboard big projects to FastAuth

```[tasklist]
### Related Issues
- [ ] https://github.com/near/mpc-recovery/issues/269
- [ ] https://github.com/near/mpc-recovery/issues/233
- [ ] https://github.com/near/mpc-recovery/issues/220
- [ ] https://github.com/near/mpc-recovery/issues/263
- [ ] https://github.com/near/mpc-recovery/issues/183
- [ ] https://github.com/near/mpc-recovery/issues/111
- [ ] https://github.com/near/mpc-recovery/issues/199
```

```[tasklist]
### Optional
- [ ] https://github.com/near/mpc-recovery/issues/244
- [ ] https://github.com/near/mpc-recovery/issues/255
```
