### ISSUE TITLE
Release new version (both signing and leader node)

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#336]
In order to avoid updating the partner list on each node we will need to release updated version of the MPC on signing nodes.

```[tasklist]
### Tasks
- [ ] https://github.com/near/mpc-recovery/issues/337
- [ ] https://github.com/near/mpc-recovery/pull/321
- [ ] https://github.com/near/mpc-recovery/issues/357
- [x] Test new SRE setup
- [x] Test if Old signing works with new Signing node
- [ ] https://github.com/near/mpc-recovery/pull/371
- [x] Fix testnet relayer (testnet and dev envs)
- [x] Coordinate with FE, make sure that they are using LB URLs (they are already pointing to right envs)
- [x] Make sure latest develop works and FE code is ready for it
- [ ] https://github.com/near/mpc-recovery/issues/379
```
```[tasklist]
### Nice to have
- [ ] https://github.com/near/mpc-recovery/issues/372
```
