### ISSUE TITLE
Resolve issues in OTLP/Graphana/Alerts

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#373]
```[tasklist]
### Tasks
- [ ] https://github.com/PagodaPlatform/SRE-Devops-team/issues/104
- [ ] https://github.com/PagodaPlatform/SRE-Devops-team/issues/103
- [ ] Make sure that we have graph of code spans
```
