### ISSUE TITLE
Recreate Grafana, Alerts, etc.

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#922]
### Description

```[tasklist]
### Tasks
- [x] Find out the cost of Synthetics
- [x] Chat ops with Slack
- [x] Synthetics Testnet
- [x] Synthetics Mainnet
- [x] Make sure people setup their Grafana account
- [x] Basic Alerts for FastAuth
- [ ] https://github.com/near/mpc/issues/908
```
